#!/bin/bash -x
# TODO import ./CONFIG test database information passed so this works on the cloud.
# Not sure what challenges that has yet, for what osm2pgsql needs to run remotely.
#
# To avoid vacuum of giant GIS database, easiest for now to do
# "dropdb gis; createdb gis" before running benchwarmer.  Then this script
# puts all the extensions back.  We can't just drop/create here because
# basic pgbench-tools work requires the database exist for starting
# snapshots of stats.

. ../../../config
. ../../../params

if [ -z "${NODES_FILE}" ] ; then
  NODES_FILE="nodes.db"
fi

if [ -z "${PLANET_FILE}" ] ; then
  PLANET_FILE="~/osm/planet-latest.osm.pbf"
fi

if [ -z "${OSMNODECACHE}" ] ; then
  OSMNODECACHE=0
fi

TESTPSQL="psql -h $TESTHOST -U $TESTUSER -p $TESTPORT -d $TESTDB"

$TESTPSQL -c 'CREATE EXTENSION postgis;'
$TESTPSQL -c 'CREATE EXTENSION hstore;'
$TESTPSQL -c 'CREATE EXTENSION pg_stat_statements;'
$TESTPSQL -c 'CREATE EXTENSION pg_buffercache;'

# TODO SETCLIENTS is a list, assigning it to a single variable is risky.
# Only the benchwarmer script knows the singular client count for a test.
# However, it turns that into "-c 2" pgbench form before calling this script.
# Here we would need an alternate communication or handling a full set of
# command line parameters to find the number; thus the kludge.
if [ -z "${SETCLIENTS}" ] ; then
  SETCLIENTS=2
fi

rm -f $NODES_FILE 
# When changing this, beware the usual style of commenting out any one line.
# That doesn't work on this form of multi-line command.
time osm2pgsql --create --slim -v \
    -H $TESTHOST -U $TESTUSER -P $TESTPORT -d $TESTDB \
    --cache ${OSMNODECACHE} --number-processes ${SETCLIENTS} \
    --flat-nodes $NODES_FILE \
    --hstore --hstore-add-index \
    $PLANET_FILE
rm -f $NODES_FILE
